aluna:
  name: "Paula Franco"


project:
  name: 'pdvCliente'
  version: '0.0.1-SNAPSHOT'
  description: 'Demo project for Spring Boot'
info:
  build:
    artifact: "pdvCliente"
    name: "pdvCliente"
    description: 'Demo project for Spring Boot'
    version: '0.0.1-SNAPSHOT'

application:
  title: ${project.name}
  version: ${project.version}

#application:
#  title: 'pdvCliente'
#  version: '0.0.1-SNAPSHOT'


#spring.banner.charset=UTF-8
#spring.banner.location=classpath:banner.txt

spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLE}
  banner:
    charset: ${SPRING_BANNER_CHARSET}
    location: ${SPRING_BANNER_LOCATION}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''

#Logging
logging:
  level:
    org.example: debug
    org.springframework.web: info